# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru


#spring.datasource
#  .url: jdbc:mysql://localhost:3306/search_engine
#  .username: root
#spring.datasource.password: dd25092001_Valy
#spring.hibernate.ddl-auto: update

server:
  port: 8080

spring:
  datasource:
    username: root
    password: dd25092001_Valy
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
      show-sql: true